### ISSUE TITLE
it works well but its too slow in CPU, does anybody implement it with GPU?

### ISSUE THREAD

**Issue by sutongkui** [zhou13/arcsim#2]

**Comment by zhou13** [comment]
The main bottleneck now is the sparse solver. Using Pardiso from MKL should help a lot. For GPU implementation, someone may want to try [cusolver](http://docs.nvidia.com/cuda/cusolver/#axzz4gSWAlUjE). However cusolver only has sparse QR factorization, which may not always faster than the current implementation.

**Comment by sutongkui** [comment]
got it! another question , we need to generate many frames to make a video, i wonder when you stop the simulation in  each frame, in my experience, for a  static body, each point in the cloth still has a velocity, although it's very slow, what's the condition that you stop it in each frame? Thanks and i wonder if you can leave your email.

**Comment by sutongkui** [comment]
got it! another question , we need to generate many frames to make a video, i wonder when you stop the simulation in each frame, in my experience, for a static body, each point in the cloth still has a velocity, although it's very slow, what's the condition that you stop it in each frame? Thanks and i wonder if you can leave your email. @zhou13

**Comment by zhou13** [comment]
I will soon update the arcsim to provide a better support of external solver so I just closed this bug.

I don't understand your question and I will not provide support for my version of arcsim.
